import type { Metadata } from "next";
import { LegalContact, LegalPage, type LegalSection } from "@/components/LegalPage";
import { siteConfig } from "@/lib/config";
import { createEmailContactUrl } from "@/lib/contactLinks";

export const metadata:Metadata={title:{absolute:"Privacy Policy | PRIME IPTV"},description:"Learn how PRIME IPTV handles information provided through orders, free trial requests and support communications.",alternates:{canonical:"/privacy"}};
const sections:LegalSection[]=[
  {id:"introduction",label:"Introduction"},{id:"information",label:"Information We Collect"},{id:"whatsapp",label:"Orders and WhatsApp"},{id:"use",label:"How We Use Information"},{id:"storage",label:"Data Storage"},{id:"sensitive",label:"Sensitive Information"},{id:"cookies",label:"Cookies and Analytics"},{id:"third-parties",label:"Third-Party Services"},{id:"security",label:"Security"},{id:"rights",label:"User Rights"},{id:"changes",label:"Changes to this Policy"},{id:"contact",label:"Contact"},
];

export default function Privacy(){const emailHref=createEmailContactUrl(siteConfig.email);return <LegalPage title="Privacy Policy" updated="August 20, 2026" description="This policy explains how information may be handled when you visit PRIME IPTV, request a service or contact support." sections={sections}>
  <section id="introduction"><h2>1. Introduction</h2><p>PRIME IPTV respects the privacy of its visitors and customers. This Privacy Policy explains the information you may choose to provide when using this website, requesting a Free 24H Trial, submitting an order request or contacting support, and how that information may be used.</p></section>
  <section id="information"><h2>2. Information We Collect</h2><p>Depending on how you interact with the website, you may be asked to provide:</p><ul><li>Full name</li><li>Email address</li><li>Phone or WhatsApp number</li><li>Country</li><li>Device type</li><li>IPTV application, when voluntarily provided</li><li>Selected subscription plan</li><li>Information you voluntarily include in a support request</li></ul><p>The website forms do not request full payment card details, CVV codes, banking passwords or OTP codes.</p></section>
  <section id="whatsapp"><h2>3. Orders and WhatsApp</h2><p>When you complete an order or Free 24H Trial form and select the WhatsApp button, the website prepares a message containing the information you entered and opens WhatsApp. You decide whether to review and send that message.</p><p>Your use of WhatsApp is also governed by WhatsApp&apos;s own terms and privacy practices. PRIME IPTV does not control how WhatsApp processes information transmitted through its service.</p></section>
  <section id="use"><h2>4. How We Use Information</h2><p>Information you provide may be used to:</p><ul><li>Respond to enquiries and support requests</li><li>Process order requests and Free 24H Trial requests</li><li>Provide configuration and setup instructions</li><li>Provide customer support</li><li>Communicate with you about a subscription</li><li>Prevent abuse or fraudulent use</li><li>Comply with applicable legal obligations</li></ul></section>
  <section id="storage"><h2>5. Data Storage</h2><p>The website&apos;s current order and trial forms primarily prepare a communication for WhatsApp. They do not automatically submit form contents to a PRIME IPTV database through a website API.</p><p>Information may still be processed or retained within communications you send, by WhatsApp, the site hosting provider or other services involved in delivering the website and communications. Their handling of information is subject to their respective practices.</p></section>
  <section id="sensitive"><h2>6. Sensitive Information</h2><p><strong>Never send passwords, banking passwords, full payment card details, CVV codes, OTP codes or other sensitive authentication information through the website forms or support chat.</strong></p></section>
  <section id="cookies"><h2>7. Cookies and Analytics</h2><p>PRIME IPTV does not currently configure non-essential analytics or advertising cookies on this website. Basic technical data may nevertheless be processed by the hosting environment as necessary to deliver and protect the site.</p><p>If analytics or other non-essential tracking technologies are introduced, this section will be updated to describe them and any choices available to visitors.</p></section>
  <section id="third-parties"><h2>8. Third-Party Services</h2><p>Certain interactions may rely on third-party services, including WhatsApp and the website hosting provider. Those providers operate under their own terms and privacy practices. PRIME IPTV does not make representations about, or control, their independent data-processing practices.</p></section>
  <section id="security"><h2>9. Security</h2><p>Reasonable technical and organizational measures are used to protect the website and the information handled through it. However, no Internet transmission or electronic storage method can be guaranteed to be completely secure. You should avoid sending information that is not necessary for your request.</p></section>
  <section id="rights"><h2>10. User Rights</h2><p>Depending on the law that applies to you, you may have rights concerning your personal information, which may include access, correction or deletion. To submit a request, contact PRIME IPTV {emailHref?<a className="text-gold underline decoration-gold/30 underline-offset-4" href={emailHref}>at {siteConfig.email}</a>:"through the official contact section"}. We may need to verify the request before acting on it.</p></section>
  <section id="changes"><h2>11. Changes to this Privacy Policy</h2><p>This Privacy Policy may be updated to reflect changes to the website, its services or applicable requirements. The “Last Updated” date at the top of this page indicates the latest revision.</p></section>
  <section id="contact"><h2>12. Contact</h2><p>For privacy questions or requests, contact PRIME IPTV using the official details below.</p><LegalContact/></section>
</LegalPage>}
