import type { Metadata } from "next";
import { LegalContact, LegalPage, type LegalSection } from "@/components/LegalPage";
import { plans } from "@/lib/pricing";

export const metadata:Metadata={title:{absolute:"Terms & Conditions | PRIME IPTV"},description:"Terms governing use of the PRIME IPTV website, subscription requests and Free 24H Trial.",alternates:{canonical:"/terms"}};
const sections:LegalSection[]=[
  {id:"acceptance",label:"Acceptance of Terms"},{id:"service",label:"Service"},{id:"plans",label:"Subscription Plans"},{id:"trial",label:"Free 24H Trial"},{id:"orders",label:"Orders"},{id:"activation",label:"Activation"},{id:"refunds",label:"Refund Policy — 24 Hours"},{id:"requirements",label:"Technical Requirements"},{id:"content",label:"Content and Availability"},{id:"intellectual-property",label:"Intellectual Property"},{id:"prohibited",label:"Prohibited Use"},{id:"suspension",label:"Access Suspension"},{id:"availability",label:"Service Availability"},{id:"liability",label:"Limitation of Liability"},{id:"changes",label:"Changes to Terms"},{id:"contact",label:"Contact"},
];

export default function Terms(){return <LegalPage title="Terms & Conditions" updated="August 20, 2026" description="These terms govern your use of the PRIME IPTV website and requests for subscriptions, trials and related support." sections={sections}>
  <section id="acceptance"><h2>1. Acceptance of Terms</h2><p>By using this website or requesting a PRIME IPTV service, you agree to these Terms & Conditions. If you do not agree, do not submit a service request.</p></section>
  <section id="service"><h2>2. Service</h2><p>PRIME IPTV provides streaming access and configuration services intended for use with supported devices and compatible applications. Features, compatibility and availability may depend on the customer&apos;s equipment, application, Internet connection and service configuration. No specific channel count, permanent quality level or uninterrupted availability is promised by these terms.</p></section>
  <section id="plans"><h2>3. Subscription Plans</h2><p>The subscription options currently displayed on the website are:</p><ul>{plans.map(plan=><li key={plan.months}><strong>{plan.name} — €{plan.price}</strong></li>)}</ul><p>Prices may change for future orders. A later price change will not retroactively alter an order that PRIME IPTV has already accepted and for which payment has been completed.</p></section>
  <section id="trial"><h2>4. Free 24H Trial</h2><p>PRIME IPTV may offer a free 24-hour trial, subject to availability. A request is prepared through the website form and then sent voluntarily by the visitor through WhatsApp. Submission does not promise immediate or automatic activation.</p><p>Where appropriate, trials may be limited to one per customer, device or household. Abusive or repeated requests may be refused. Requesting or using a trial does not create an obligation to purchase a subscription.</p></section>
  <section id="orders"><h2>5. Orders</h2><p>The current order process works as follows:</p><ol><li>The customer selects a subscription plan.</li><li>The customer completes the website order form.</li><li>The customer selects “Continue on WhatsApp.”</li><li>WhatsApp opens with a prepared order request.</li><li>The customer reviews and voluntarily sends the message.</li><li>PRIME IPTV communicates with the customer about the next steps.</li></ol><p>Completing the website form or opening WhatsApp does not itself constitute payment or final acceptance of an order.</p></section>
  <section id="activation"><h2>6. Activation</h2><p>Activation takes place after an order has been processed and, where payment is required, after payment has been confirmed. Processing time may vary according to the request and circumstances. No precise activation time is guaranteed by these terms.</p></section>
  <section id="refunds"><h2>7. Refund Policy — 24 Hours</h2><p><strong>Refund requests must be submitted within 24 hours of the initial activation of the paid subscription.</strong></p><p>A request submitted after this period may be refused, subject to any mandatory rights under applicable law. Refund requests are reviewed to verify the relevant order, activation and reported issue; a refund is not automatically guaranteed in every case.</p><p>Customers must submit a request through the official PRIME IPTV contact details shown on this website. Nothing in this policy excludes or restricts consumer rights that cannot lawfully be excluded or restricted.</p></section>
  <section id="requirements"><h2>8. Technical Requirements</h2><p>The customer is responsible for having an appropriate Internet connection, a compatible device and a compatible application where required. Playback quality may be affected by Internet stability, Wi-Fi conditions, the Internet service provider, device performance, the selected application and external network factors.</p></section>
  <section id="content"><h2>9. Content and Availability</h2><p>The available catalogue may include different categories of films, series, television and other content. Catalogue content and availability may change over time and may differ according to the applicable service configuration.</p><p>PRIME IPTV does not claim affiliation with any third-party platform or brand unless that affiliation is expressly stated and authorized. Any reference to a third-party brand is for identification purposes only and does not by itself imply partnership, sponsorship or endorsement.</p></section>
  <section id="intellectual-property"><h2>10. Intellectual Property</h2><p>Third-party trademarks, logos and content remain the property of their respective owners. PRIME IPTV does not claim ownership of third-party marks. The PRIME IPTV website design, branding and original site materials may not be copied or exploited without authorization, subject to applicable law.</p></section>
  <section id="prohibited"><h2>11. Prohibited Use</h2><p>Users must not:</p><ul><li>Abusively share access credentials</li><li>Resell access without authorization</li><li>Attempt unauthorized access to the website or related systems</li><li>Use abusive automation or interfere with service operation</li><li>Engage in fraud or misrepresentation</li><li>Use the service in violation of applicable law</li></ul></section>
  <section id="suspension"><h2>12. Account / Access Suspension</h2><p>Access may be suspended or terminated in cases of fraud, abuse, a material breach of these terms or prohibited use, subject to applicable law and any rights that cannot be waived.</p></section>
  <section id="availability"><h2>13. Service Availability</h2><p>Internet-based services may experience maintenance, temporary interruptions, network problems or technical changes. PRIME IPTV does not promise 100% uptime or uninterrupted operation.</p></section>
  <section id="liability"><h2>14. Limitation of Liability</h2><p>To the extent permitted by applicable law, PRIME IPTV is not responsible for service issues caused by circumstances outside its reasonable control, including a customer&apos;s Internet outage, incompatible device, third-party application, ISP restriction or failure, or other third-party service.</p><p>Nothing in these terms excludes or limits liability where such exclusion or limitation is prohibited by applicable law.</p></section>
  <section id="changes"><h2>15. Changes to Terms</h2><p>These Terms & Conditions may be updated to reflect changes to the website, services or applicable requirements. The “Last Updated” date at the top identifies the latest revision. Updated terms apply prospectively from their publication, subject to applicable law.</p></section>
  <section id="contact"><h2>16. Contact</h2><p>For order, trial, support or refund questions, contact PRIME IPTV through the official details below.</p><LegalContact/></section>
</LegalPage>}
