export type ChatAction =
  | { type: "suggestion"; label: string; message: string }
  | { type: "anchor"; label: string; href: "#plans" | "/terms" }
  | { type: "whatsapp"; label: string }
  | { type: "email"; label: string }
  | { type: "trial"; label: string };

export type KnowledgeEntry = {
  id: string;
  keywords: string[];
  aliases: string[];
  answer: string;
  actions?: ChatAction[];
};

const deviceActions: ChatAction[] = ["Smart TV", "Android", "iPhone / iPad", "Fire TV", "Windows / Mac", "MAG / TV Box"].map(label => ({ type: "suggestion", label, message: `How do I install IPTV on ${label}?` }));

export const chatbotKnowledge: KnowledgeEntry[] = [
  { id:"what-is-iptv", keywords:["iptv","meaning","stand"], aliases:["what is iptv","whats iptv","iptv meaning","what does iptv mean"], answer:"IPTV stands for Internet Protocol Television. It refers to television content delivered through an internet connection instead of traditional terrestrial, satellite or cable broadcasting." },
  { id:"m3u", keywords:["m3u","playlist","playlist url"], aliases:["what is m3u","whats m3u","m3u meaning","m3u url","playlist url"], answer:"M3U is a playlist file or URL commonly used by IPTV applications to load available streams or media entries." },
  { id:"epg", keywords:["epg","program guide","schedule"], aliases:["what is epg","whats epg","epg meaning","what does epg stand for"], answer:"EPG stands for Electronic Program Guide. It displays scheduling information such as program names, times and upcoming content when supported by the service and player." },
  { id:"xtream", keywords:["xtream","xc","xtream api","xc api"], aliases:["what are xtream codes","what is xtream","xtream codes","xtream api","xc api","xc"], answer:"Xtream Codes API credentials are a login method supported by many IPTV players. They typically use a server URL, username and password instead of importing an M3U playlist manually." },
  { id:"vod", keywords:["vod","video on demand"], aliases:["what is vod","vod meaning","what does vod mean"], answer:"VOD stands for Video on Demand. It describes content that can be selected and played when the viewer chooses rather than following a live broadcast schedule." },
  { id:"ppv", keywords:["ppv","pay per view"], aliases:["what is ppv","ppv meaning","what does ppv mean"], answer:"PPV stands for Pay-Per-View, a term used for events or content offered individually rather than as part of regular programming. Availability depends on the service." },
  { id:"isp", keywords:["isp","internet provider"], aliases:["what is an isp","what is isp","isp meaning"], answer:"ISP stands for Internet Service Provider — the company that provides your internet connection." },
  { id:"vpn", keywords:["vpn","virtual private network"], aliases:["what is a vpn","what is vpn","vpn meaning","do i need vpn"], answer:"VPN stands for Virtual Private Network. It creates an encrypted connection between your device and a VPN server. Whether you need one depends on your network and local requirements." },
  { id:"stb", keywords:["stb","set top box"], aliases:["what is stb","stb meaning","what does stb mean"], answer:"STB stands for Set-Top Box, a device connected to a television to receive and display digital content." },
  { id:"mag", keywords:["mag","mag box","mag device"], aliases:["what is a mag box","mag box","mag device"], answer:"MAG devices are set-top boxes commonly used with IPTV-compatible services and portals. Compatibility depends on the specific model and service configuration." },
  { id:"apk", keywords:["apk","android package"], aliases:["what is apk","what is an apk","apk meaning"], answer:"APK stands for Android Package Kit. It is the file format used to install Android applications. Only install applications from sources you trust." },
  { id:"uhd", keywords:["4k","uhd","3840 2160"], aliases:["what is 4k","what is uhd","4k meaning","uhd meaning"], answer:"4K or UHD typically refers to video around 3840×2160 resolution. Actual playback quality depends on the source, device and internet connection." },
  { id:"fhd", keywords:["fhd","full hd","1080"], aliases:["what is fhd","fhd meaning","full hd"], answer:"FHD means Full HD and normally refers to 1920×1080 resolution." },
  { id:"hd", keywords:["hd","high definition","720"], aliases:["what is hd","hd meaning","high definition"], answer:"HD means High Definition and commonly refers to 720p or similar high-definition video resolutions." },
  { id:"buffering", keywords:["buffering","buffer","lagging","freezing","stuttering","stream stops","channels freeze","keeps freezing"], aliases:["why is my iptv buffering","my iptv keeps freezing","iptv lagging","iptv freezing","channels freezing"], answer:"Buffering, freezing or lag can be caused by network congestion, Wi-Fi instability, insufficient bandwidth, device performance or temporary server/network conditions.\n\nTry these steps:\n1. Restart your router.\n2. Restart your IPTV device or app.\n3. Test your internet connection.\n4. Try an Ethernet connection if possible.\n5. Close unnecessary applications.\n6. Test another network if available.\n7. Contact support if the issue continues." },
  { id:"speed", keywords:["internet speed","bandwidth","connection speed","how fast"], aliases:["how fast should my internet be","what internet speed do i need","required speed"], answer:"Required speed depends on video quality, network stability and other devices using your connection. A stable connection is often more important than the maximum advertised speed. Higher resolutions such as 4K generally require significantly more bandwidth than HD." },
  { id:"devices", keywords:["devices","compatible","supported","what devices","device work"], aliases:["which devices are supported","what devices work","compatible devices"], answer:"Prime IPTV is designed to work with common IPTV-compatible devices and players, including Smart TVs, Android TV, Fire TV, smartphones, tablets, Windows, macOS and compatible TV boxes. Exact compatibility can depend on the application or device model." },
  { id:"iphone", keywords:["iphone","ios","ipad","apple phone"], aliases:["does it work on iphone","can i use it on iphone","iphone","ipad"], answer:"You can use an IPTV-compatible player available for iPhone or iPad when supported by your subscription configuration." },
  { id:"android", keywords:["android","android phone","android tv","tv box"], aliases:["does it work on android","android","android tv"], answer:"Android phones, Android TV devices and compatible TV boxes can use an IPTV-compatible player. Follow the setup instructions provided for your subscription and device." },
  { id:"smart-tv", keywords:["smart tv","samsung tv","lg tv","television"], aliases:["does it work smart tv","smart tv","samsung tv","lg tv"], answer:"A Smart TV can use the service when it supports a compatible IPTV application. Application availability and setup can vary by television model and platform." },
  { id:"fire-tv", keywords:["firestick","fire stick","amazon fire tv","firetv","fire tv"], aliases:["does it work on firestick","firestick","fire tv"], answer:"Fire TV devices can use compatible IPTV applications according to your subscription configuration. Follow the device-specific setup instructions supplied after activation." },
  { id:"installation", keywords:["install","installation","setup","configure","how to"], aliases:["how do i install iptv","how to install","installation help","setup iptv"], answer:"Installation depends on your device. After your order is activated, follow the setup instructions provided for your device and install a compatible IPTV player when required.\n\nTell me which device you use and I can guide you.", actions:deviceActions },
  { id:"activation", keywords:["activation","activate","receive subscription","order processed","receive details"], aliases:["how long does activation take","when will i receive my subscription","activation time"], answer:"Activation time can vary. Once your order is processed, you will receive the information required to configure your service. Contact support if you have not received your details within the expected processing time." },
  { id:"renewal", keywords:["renew","renewal","extend subscription","expired","expiration"], aliases:["how do i renew","subscription expired","renew subscription","expired account"], answer:"If your subscription is close to expiration or has expired, contact Prime IPTV support to renew or choose a new plan.", actions:[{type:"whatsapp",label:"Contact Support"}] },
  { id:"credentials", keywords:["username","password","login","credentials","server url","portal","m3u link"], aliases:["where are my credentials","login details","server url","m3u link"], answer:"Your connection details depend on the setup method used for your subscription. Do not publicly share your username, password, playlist URL or portal credentials." },
  { id:"payment", keywords:["payment","pay","card","paypal","checkout"], aliases:["how can i pay","payment methods","pay for subscription"], answer:"Available payment options are confirmed during the order process. For your security, never share full card details, verification codes or banking passwords in chat." },
  { id:"free-trial", keywords:["free trial","trial","24h trial","free test","demo","test account","can i try","try before buying"], aliases:["can i try","free trial","24h trial","free test","try before buying","test account"], answer:"Yes. You can request a free 24-hour trial to test Prime IPTV on your device before choosing a subscription.", actions:[{type:"trial",label:"Request Free Trial"}] },
];

export const initialSuggestions = ["What is IPTV?","Which devices are supported?","How do I install IPTV?","What is M3U?","What is EPG?","My IPTV is buffering","View subscription plans"];
